# Experiment 14
## Data Normalisation and Data Type Conversion
## Name - Krish Joshi
## Batch - A-3
## PRN - 25070123064

In [87]:
#Data set
import pandas as pd
import numpy as np
data = {
    'Product':['Laptop','Tablet','Headphones','Smartwatch','Camera','Mobile'],
    'Price':[55000,20000,10000,2000,15000,30000],
    'Units_Sold':[25,60,35,80,50,15],
    'Discount':[10,15,12,20,18,8]
}
df = pd.DataFrame(data)
df

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Tablet  20000          60        15
2  Headphones  10000          35        12
3  Smartwatch   2000          80        20
4      Camera  15000          50        18
5      Mobile  30000          15         8

In [88]:
#Min-Max Normalisation
#Min-Max Normalisation for price

df['Price_MinMax']=(df['Price']-df['Price'].min())/(df['Price'].max()-df['Price'].min())
df

      Product  Price  Units_Sold  Discount  Price_MinMax
0      Laptop  55000          25        10      1.000000
1      Tablet  20000          60        15      0.339623
2  Headphones  10000          35        12      0.150943
3  Smartwatch   2000          80        20      0.000000
4      Camera  15000          50        18      0.245283
5      Mobile  30000          15         8      0.528302

In [89]:
# Z-score normalisation
df['Units_Zscore']=(df['Units_Sold']-df['Units_Sold'].mean())/df['Units_Sold'].std()
df

      Product  Price  Units_Sold  Discount  Price_MinMax  Units_Zscore
0      Laptop  55000          25        10      1.000000     -0.799885
1      Tablet  20000          60        15      0.339623      0.660775
2  Headphones  10000          35        12      0.150943     -0.382554
3  Smartwatch   2000          80        20      0.000000      1.495437
4      Camera  15000          50        18      0.245283      0.243443
5      Mobile  30000          15         8      0.528302     -1.217216

In [90]:
#Decimal Scaling
df['Price_Decimal']=df['Price']/10000
df

,Product,Price,Units_Sold,Discount,Price_MinMax,Units_Zscore,Price_Decimal
0,Laptop,55000,25,10,1.000000,-0.799885,5.5
1,Tablet,20000,60,15,0.339623,0.660775,2.0
2,Headphones,10000,35,12,0.150943,-0.382554,1.0
3,Smartwatch,2000,80,20,0.000000,1.495437,0.2
4,Camera,15000,50,18,0.245283,0.243443,1.5
5,Mobile,30000,15,8,0.528302,-1.217216,3.0

# PART B- Turning categorical variable to quantitative variables in Python

In [91]:
import pandas as pd
import numpy as np
data = {
    'Order_ID':[101,102,103,104,105,106],
    'Customer_Gender':['Male','Female','Male','Female','Male','Female'],
    'Payment_Method':['COD','UPI','Debit Card','UPI','Credit Card','Debit Card'],
    'Product_Category':['Electronics','Clothing','Electronics','Clothing','Electronics','Clothing'],
    'City':['Pune','Delhi','Mumbai','Chennai','Surat','Patiala'],
    'Order_Value':[1500,800,1200,900,2000,1000]
}
df = pd.DataFrame(data)
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value
0,101,Male,COD,Electronics,Pune,1500
1,102,Female,UPI,Clothing,Delhi,800
2,103,Male,Debit Card,Electronics,Mumbai,1200
3,104,Female,UPI,Clothing,Chennai,900
4,105,Male,Credit Card,Electronics,Surat,2000
5,106,Female,Debit Card,Clothing,Patiala,1000

In [92]:
#Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label
0,101,Male,COD,Electronics,Pune,1500,1
1,102,Female,UPI,Clothing,Delhi,800,0
2,103,Male,Debit Card,Electronics,Mumbai,1200,1
3,104,Female,UPI,Clothing,Chennai,900,0
4,105,Male,Credit Card,Electronics,Surat,2000,1
5,106,Female,Debit Card,Clothing,Patiala,1000,0

In [93]:
#Method-2 One-Hot Encoding
df_encoded= pd.get_dummies(df, columns=['Payment_Method'])
df_encoded

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Gender_Label,Payment_Method_COD,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,1500,1,True,False,False,False
1,102,Female,Clothing,Delhi,800,0,False,False,False,True
2,103,Male,Electronics,Mumbai,1200,1,False,False,True,False
3,104,Female,Clothing,Chennai,900,0,False,False,False,True
4,105,Male,Electronics,Surat,2000,1,False,True,False,False
5,106,Female,Clothing,Patiala,1000,0,False,False,True,False

#New

In [94]:
df=pd.read_csv('/content/amazon_products_dataset_Expt-14.csv')

In [95]:
# Min-Max Normalisation
df['Price_MinMax']=(df['Price']-df['Price'].min())/(df['Price'].max())
df['Units_Sold_MinMax']=(df['Units_Sold']-df['Units_Sold'].min())/(df['Units_Sold'].max())
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Units_Sold_MinMax
0,P101,Wireless Mouse,799,4.3,1520,350,0.020001,0.459016
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048002,0.245902
2,P103,USB Keyboard,699,4.1,870,180,0.016001,0.180328
3,P104,Gaming Headset,2499,4.6,2100,410,0.088004,0.557377
4,P105,Smartwatch,3999,4.4,3050,520,0.148006,0.737705
5,P106,Power Bank,1199,4.2,1750,390,0.036001,0.524590
6,P107,Laptop Stand,899,4.0,620,140,0.024001,0.114754
7,P108,Webcam,1899,4.3,1120,260,0.064003,0.311475
8,P109,Portable SSD,5499,4.7,1850,330,0.208008,0.426230
9,P110,Wireless Charger,999,4.2,760,190,0.028001,0.196721
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.308012,0.885246
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.172007,0.360656
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052002,0.442623
13,P114,Tablet Stand,699,4.1,540,120,0.016001,0.081967
14,P115,USB Hub,899,4.2,870,200,0.024001,0.213115
15,P116,External Hard Drive,6499,4.6,2300,310,0.248010,0.393443
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036001,0.229508
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068003,0.573770
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.108004,0.754098
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040002,0.311475
20,P121,Phone Holder,499,4.0,420,150,0.008000,0.131148
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.088004,0.393443
22,P123,Portable Monitor,8999,4.6,1250,170,0.348014,0.163934
23,P124,Smart Plug,799,4.2,720,210,0.020001,0.229508
24,P125,WiFi Router,3499,4.5,2100,390,0.128005,0.524590
25,P126,Graphics Tablet,4599,4.4,980,160,0.172007,0.147541
26,P127,VR Headset,12999,4.7,3100,140,0.508020,0.114754
27,P128,Microphone,2199,4.3,1300,270,0.076003,0.327869
28,P129,Smart Light Bulb,699,4.2,880,240,0.016001,0.278689
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048002,0.311475
30,P131,Action Camera,9999,4.6,2100,200,0.388016,0.213115
31,P132,Smart Doorbell,5999,4.5,1750,180,0.228009,0.180328
32,P133,Streaming Stick,3499,4.4,2500,430,0.128005,0.590164
33,P134,Portable Projector,11999,4.6,1450,120,0.468019,0.081967
34,P135,Gaming Chair,15999,4.7,2100,90,0.628025,0.032787
35,P136,Desk Organizer,599,4.1,450,160,0.012000,0.147541
36,P137,USB Flash Drive,799,4.2,900,320,0.020001,0.409836
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000,0.508197
38,P139,Laptop Sleeve,999,4.3,720,210,0.028001,0.229508
39,P140,Wireless Presenter,1499,4.4,520,130,0.048002,0.098361
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.108004,0.131148
41,P142,Smart Thermostat,10999,4.6,1200,110,0.428017,0.065574
42,P143,Security Camera,4999,4.4,2100,260,0.188008,0.311475
43,P144,Drone Camera,24999,4.7,1800,70,0.988040,0.000000
44,P145,Electric Kettle,1999,4.3,1400,310,0.068003,0.393443
45,P146,Air Fryer,7999,4.6,2200,200,0.308012,0.213115
46,P147,Robot Vacuum,18999,4.5,1650,120,0.748030,0.081967
47,P148,Smart Scale,2499,4.4,980,170,0.088004,0.163934
48,P149,Digital Photo Frame,3499,4.3,870,150,0.128005,0.131148
49,P150,Portable Fan,999,4.2,760,240,0.028001,0.278689

In [96]:
# Z-Score Normalisation
df['Price_Zscore']=(df['Price']-df['Price'].mean())/df['Price'].std()
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Units_Sold_MinMax,Price_Zscore
0,P101,Wireless Mouse,799,4.3,1520,350,0.020001,0.459016,-0.692019
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048002,0.245902,-0.557310
2,P103,USB Keyboard,699,4.1,870,180,0.016001,0.180328,-0.711263
3,P104,Gaming Headset,2499,4.6,2100,410,0.088004,0.557377,-0.364869
4,P105,Smartwatch,3999,4.4,3050,520,0.148006,0.737705,-0.076207
5,P106,Power Bank,1199,4.2,1750,390,0.036001,0.524590,-0.615043
6,P107,Laptop Stand,899,4.0,620,140,0.024001,0.114754,-0.672775
7,P108,Webcam,1899,4.3,1120,260,0.064003,0.311475,-0.480334
8,P109,Portable SSD,5499,4.7,1850,330,0.208008,0.426230,0.212455
9,P110,Wireless Charger,999,4.2,760,190,0.028001,0.196721,-0.653531
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.308012,0.885246,0.693559
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.172007,0.360656,0.039258
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052002,0.442623,-0.538066
13,P114,Tablet Stand,699,4.1,540,120,0.016001,0.081967,-0.711263
14,P115,USB Hub,899,4.2,870,200,0.024001,0.213115,-0.672775
15,P116,External Hard Drive,6499,4.6,2300,310,0.248010,0.393443,0.404897
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036001,0.229508,-0.615043
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068003,0.573770,-0.461090
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.108004,0.754098,-0.268648
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040002,0.311475,-0.595799
20,P121,Phone Holder,499,4.0,420,150,0.008000,0.131148,-0.749752
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.088004,0.393443,-0.364869
22,P123,Portable Monitor,8999,4.6,1250,170,0.348014,0.163934,0.886000
23,P124,Smart Plug,799,4.2,720,210,0.020001,0.229508,-0.692019
24,P125,WiFi Router,3499,4.5,2100,390,0.128005,0.524590,-0.172428
25,P126,Graphics Tablet,4599,4.4,980,160,0.172007,0.147541,0.039258
26,P127,VR Headset,12999,4.7,3100,140,0.508020,0.114754,1.655766
27,P128,Microphone,2199,4.3,1300,270,0.076003,0.327869,-0.422601
28,P129,Smart Light Bulb,699,4.2,880,240,0.016001,0.278689,-0.711263
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048002,0.311475,-0.557310
30,P131,Action Camera,9999,4.6,2100,200,0.388016,0.213115,1.078442
31,P132,Smart Doorbell,5999,4.5,1750,180,0.228009,0.180328,0.308676
32,P133,Streaming Stick,3499,4.4,2500,430,0.128005,0.590164,-0.172428
33,P134,Portable Projector,11999,4.6,1450,120,0.468019,0.081967,1.463325
34,P135,Gaming Chair,15999,4.7,2100,90,0.628025,0.032787,2.233090
35,P136,Desk Organizer,599,4.1,450,160,0.012000,0.147541,-0.730508
36,P137,USB Flash Drive,799,4.2,900,320,0.020001,0.409836,-0.692019
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000,0.508197,-0.788240
38,P139,Laptop Sleeve,999,4.3,720,210,0.028001,0.229508,-0.653531
39,P140,Wireless Presenter,1499,4.4,520,130,0.048002,0.098361,-0.557310
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.108004,0.131148,-0.268648
41,P142,Smart Thermostat,10999,4.6,1200,110,0.428017,0.065574,1.270883
42,P143,Security Camera,4999,4.4,2100,260,0.188008,0.311475,0.116235
43,P144,Drone Camera,24999,4.7,1800,70,0.988040,0.000000,3.965063
44,P145,Electric Kettle,1999,4.3,1400,310,0.068003,0.393443,-0.461090
45,P146,Air Fryer,7999,4.6,2200,200,0.308012,0.213115,0.693559
46,P147,Robot Vacuum,18999,4.5,1650,120,0.748030,0.081967,2.810415
47,P148,Smart Scale,2499,4.4,980,170,0.088004,0.163934,-0.364869
48,P149,Digital Photo Frame,3499,4.3,870,150,0.128005,0.131148,-0.172428
49,P150,Portable Fan,999,4.2,760,240,0.028001,0.278689,-0.653531

In [97]:
# Decimal Scaling
df['Price_Decimal']=df['Price']/10000
df['Reviews_Decimal']=df['Reviews']/10000
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Units_Sold_MinMax,Price_Zscore,Price_Decimal,Reviews_Decimal
0,P101,Wireless Mouse,799,4.3,1520,350,0.020001,0.459016,-0.692019,0.0799,0.152
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048002,0.245902,-0.557310,0.1499,0.098
2,P103,USB Keyboard,699,4.1,870,180,0.016001,0.180328,-0.711263,0.0699,0.087
3,P104,Gaming Headset,2499,4.6,2100,410,0.088004,0.557377,-0.364869,0.2499,0.210
4,P105,Smartwatch,3999,4.4,3050,520,0.148006,0.737705,-0.076207,0.3999,0.305
5,P106,Power Bank,1199,4.2,1750,390,0.036001,0.524590,-0.615043,0.1199,0.175
6,P107,Laptop Stand,899,4.0,620,140,0.024001,0.114754,-0.672775,0.0899,0.062
7,P108,Webcam,1899,4.3,1120,260,0.064003,0.311475,-0.480334,0.1899,0.112
8,P109,Portable SSD,5499,4.7,1850,330,0.208008,0.426230,0.212455,0.5499,0.185
9,P110,Wireless Charger,999,4.2,760,190,0.028001,0.196721,-0.653531,0.0999,0.076
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.308012,0.885246,0.693559,0.7999,0.420
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.172007,0.360656,0.039258,0.4599,0.210
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052002,0.442623,-0.538066,0.1599,0.130
13,P114,Tablet Stand,699,4.1,540,120,0.016001,0.081967,-0.711263,0.0699,0.054
14,P115,USB Hub,899,4.2,870,200,0.024001,0.213115,-0.672775,0.0899,0.087
15,P116,External Hard Drive,6499,4.6,2300,310,0.248010,0.393443,0.404897,0.6499,0.230
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036001,0.229508,-0.615043,0.1199,0.076
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068003,0.573770,-0.461090,0.1999,0.160
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.108004,0.754098,-0.268648,0.2999,0.350
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040002,0.311475,-0.595799,0.1299,0.098
20,P121,Phone Holder,499,4.0,420,150,0.008000,0.131148,-0.749752,0.0499,0.042
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.088004,0.393443,-0.364869,0.2499,0.145
22,P123,Portable Monitor,8999,4.6,1250,170,0.348014,0.163934,0.886000,0.8999,0.125
23,P124,Smart Plug,799,4.2,720,210,0.020001,0.229508,-0.692019,0.0799,0.072
24,P125,WiFi Router,3499,4.5,2100,390,0.128005,0.524590,-0.172428,0.3499,0.210
25,P126,Graphics Tablet,4599,4.4,980,160,0.172007,0.147541,0.039258,0.4599,0.098
26,P127,VR Headset,12999,4.7,3100,140,0.508020,0.114754,1.655766,1.2999,0.310
27,P128,Microphone,2199,4.3,1300,270,0.076003,0.327869,-0.422601,0.2199,0.130
28,P129,Smart Light Bulb,699,4.2,880,240,0.016001,0.278689,-0.711263,0.0699,0.088
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048002,0.311475,-0.557310,0.1499,0.099
30,P131,Action Camera,9999,4.6,2100,200,0.388016,0.213115,1.078442,0.9999,0.210
31,P132,Smart Doorbell,5999,4.5,1750,180,0.228009,0.180328,0.308676,0.5999,0.175
32,P133,Streaming Stick,3499,4.4,2500,430,0.128005,0.590164,-0.172428,0.3499,0.250
33,P134,Portable Projector,11999,4.6,1450,120,0.468019,0.081967,1.463325,1.1999,0.145
34,P135,Gaming Chair,15999,4.7,2100,90,0.628025,0.032787,2.233090,1.5999,0.210
35,P136,Desk Organizer,599,4.1,450,160,0.012000,0.147541,-0.730508,0.0599,0.045
36,P137,USB Flash Drive,799,4.2,900,320,0.020001,0.409836,-0.692019,0.0799,0.090
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000,0.508197,-0.788240,0.0299,0.060
38,P139,Laptop Sleeve,999,4.3,720,210,0.028001,0.229508,-0.653531,0.0999,0.072
39,P140,Wireless Presenter,1499,4.4,520,130,0.048002,0.098361,-0.557310,0.1499,0.052
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.108004,0.131148,-0.268648,0.2999,0.085
41,P142,Smart Thermostat,10999,4.6,1200,110,0.428017,0.065574,1.270883,1.0999,0.120
42,P143,Security Camera,4999,4.4,2100,260,0.188008,0.311475,0.116235,0.4999,0.210
43,P144,Drone Camera,24999,4.7,1800,70,0.988040,0.000000,3.965063,2.4999,0.180
44,P145,Electric Kettle,1999,4.3,1400,310,0.068003,0.393443,-0.461090,0.1999,0.140
45,P146,Air Fryer,7999,4.6,2200,200,0.308012,0.213115,0.693559,0.7999,0.220
46,P147,Robot Vacuum,18999,4.5,1650,120,0.748030,0.081967,2.810415,1.8999,0.165
47,P148,Smart Scale,2499,4.4,980,170,0.088004,0.163934,-0.364869,0.2499,0.098
48,P149,Digital Photo Frame,3499,4.3,870,150,0.128005,0.131148,-0.172428,0.3499,0.087
49,P150,Portable Fan,999,4.2,760,240,0.028001,0.278689,-0.653531,0.0999,0.076

In [98]:
#Turning Categorical variables into quantitative variables
df=pd.read_csv('/content/Student-Dataset.csv')
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [99]:
#Label encoding placement stats
df['Placement_Label']=le.fit_transform(df['Placement_Status'])
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label
0,101,Female,Computer,8.2,0,92,Placed,450000,1
1,102,Male,IT,7.5,1,85,Not Placed,0,0
2,103,Female,ENTC,9.1,0,96,Placed,550000,1
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,0
4,105,Female,Computer,8.7,0,88,Placed,480000,1
5,106,Male,Civil,7.2,3,72,Not Placed,0,0
6,107,Female,IT,8.9,0,91,Placed,500000,1
7,108,Male,Computer,6.5,1,80,Not Placed,0,0
8,109,Female,ENTC,7.8,0,84,Placed,420000,1
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,0

In [100]:
# One-Hot Encoding - Department
df_encoded = pd.get_dummies(df, columns=['Department'])
df_encoded

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label,Department_Civil,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,1,False,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,0,False,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,1,False,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,0,False,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,1,False,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,0,True,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,1,False,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,0,False,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,1,False,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,0,False,False,False,False,True

In [101]:
# Dummy encoding - Department
df_dummy = pd.get_dummies(df, columns=['Department'], drop_first=True)
df_dummy

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,1,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,0,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,1,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,0,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,1,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,0,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,1,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,0,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,1,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,0,False,False,False,True