# Experiment 13
# Data binning and data formatting using python
## Name - Krish Joshi
## PRN - 25070123064
## Batch - A3

In [ ]:
import pandas as pd
import numpy as np
data = {
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,45000],
    'Units_Sold':[25,60,35,80,50,15]
}
df = pd.DataFrame(data)
df

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [ ]:
# Data binning
bins = [0,10000,30000,60000]
labels = ['Low','Medium','High']
df['Price_Category'] = pd.cut(df['Price'],bins=bins,labels=labels)
df

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [ ]:
# Binning units sold
bins2 = [0,30,60,100]
labels2 = ['Low Sales','Medium Sales','High Sales']
df['Sales_Category'] = pd.cut(df['Units_Sold'],bins=bins2,labels=labels2)
df

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000          25           High      Low Sales
1      Mobile  20000          60         Medium   Medium Sales
2      Tablet  30000          35         Medium   Medium Sales
3  Headphones   2000          80            Low     High Sales
4  Smartwatch   8000          50            Low   Medium Sales
5      Camera  45000          15           High      Low Sales

In [ ]:
# Data formatting
# Convert Data type
print(df.dtypes)
df['Price'] = df['Price'].astype(float)
df['Units_Sold'] = df['Units_Sold'].astype(int)
df
#print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object

      Product    Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000.0          25           High      Low Sales
1      Mobile  20000.0          60         Medium   Medium Sales
2      Tablet  30000.0          35         Medium   Medium Sales
3  Headphones   2000.0          80            Low     High Sales
4  Smartwatch   8000.0          50            Low   Medium Sales
5      Camera  45000.0          15           High      Low Sales

In [ ]:
df

      Product    Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000.0          25           High      Low Sales
1      Mobile  20000.0          60         Medium   Medium Sales
2      Tablet  30000.0          35         Medium   Medium Sales
3  Headphones   2000.0          80            Low     High Sales
4  Smartwatch   8000.0          50            Low   Medium Sales
5      Camera  45000.0          15           High      Low Sales

In [ ]:
# Convert text to uppercase
df['Product'] = df['Product'].str.upper()
df

      Product    Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000.0          25           High      Low Sales
1      MOBILE  20000.0          60         Medium   Medium Sales
2      TABLET  30000.0          35         Medium   Medium Sales
3  HEADPHONES   2000.0          80            Low     High Sales
4  SMARTWATCH   8000.0          50            Low   Medium Sales
5      CAMERA  45000.0          15           High      Low Sales

In [ ]:
# Additional operations
# Sort data
sorted_df = df.sort_values(by='Price')
sorted_df

      Product    Price  Units_Sold Price_Category Sales_Category
3  HEADPHONES   2000.0          80            Low     High Sales
4  SMARTWATCH   8000.0          50            Low   Medium Sales
1      MOBILE  20000.0          60         Medium   Medium Sales
2      TABLET  30000.0          35         Medium   Medium Sales
5      CAMERA  45000.0          15           High      Low Sales
0      LAPTOP  55000.0          25           High      Low Sales

In [ ]:
# Display unique values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [ ]:
#Dataset: Food Delivery Orders
data = {
    'Order_ID':[1,2,3,4,5,6,7,8],
    'Order_Value':[250,450,120,600,300,150,500,220],
    'Delivery_Time':[30,45,15,60,20,50,28,35],
    'Distance_km':[5,10,3,8,6,10,9,4]
}
df = pd.DataFrame(data)
df

   Order_ID  Order_Value  Delivery_Time  Distance_km
0         1          250             30            5
1         2          450             45           10
2         3          120             15            3
3         4          600             60            8
4         5          300             20            6
5         6          150             50           10
6         7          500             28            9
7         8          220             35            4

In [ ]:
bins3 = [0,20,40,60]
labels3 = ['Short','Medium','Long']
df['Delivery_Category'] = pd.cut(df['Delivery_Time'],bins=bins3,labels=labels3)
df

   Order_ID  Order_Value  Delivery_Time  Distance_km Delivery_Category
0         1          250             30            5            Medium
1         2          450             45           10              Long
2         3          120             15            3             Short
3         4          600             60            8              Long
4         5          300             20            6             Short
5         6          150             50           10              Long
6         7          500             28            9            Medium
7         8          220             35            4            Medium

In [ ]:
bins4 = [0,200,400,600]
labels4 = ['Cheap','Expensive','Gourmet']
df['Price_Category'] = pd.cut(df['Order_Value'],bins=bins4,labels=labels4)
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Delivery_Category,Price_Category
0,1,250,30,5,Medium,Expensive
1,2,450,45,10,Long,Gourmet
2,3,120,15,3,Short,Cheap
3,4,600,60,8,Long,Gourmet
4,5,300,20,6,Short,Expensive
5,6,150,50,10,Long,Cheap
6,7,500,28,9,Medium,Gourmet
7,8,220,35,4,Medium,Expensive

In [ ]:
bins5 = [0,3,6,10]
labels5 = ['Close','Medium','Far']
df['Distance_Category'] = pd.cut(df['Distance_km'],bins=bins5,labels=labels5)
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Delivery_Category,Price_Category,Distance_Category
0,1,250,30,5,Medium,Expensive,Medium
1,2,450,45,10,Long,Gourmet,Far
2,3,120,15,3,Short,Cheap,Close
3,4,600,60,8,Long,Gourmet,Far
4,5,300,20,6,Short,Expensive,Medium
5,6,150,50,10,Long,Cheap,Far
6,7,500,28,9,Medium,Gourmet,Far
7,8,220,35,4,Medium,Expensive,Medium

In [ ]:
#Data Formatting
#Convert Distance to Float
df['Distance_km'] = df['Distance_km'].astype(float)
df.dtypes

Order_ID                int64
Order_Value             int64
Delivery_Time           int64
Distance_km           float64
Delivery_Category    category
Price_Category       category
Distance_Category    category
dtype: object

In [ ]:
#Convert Order_ID to uppercase
df['Price_Category'] = df['Price_Category'].astype(str)
df.dtypes

Order_ID                int64
Order_Value             int64
Delivery_Time           int64
Distance_km           float64
Delivery_Category    category
Price_Category         object
Distance_Category    category
dtype: object

In [ ]:
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Delivery_Category,Price_Category,Distance_Category
0,1,250,30,5.0,Medium,Expensive,Medium
1,2,450,45,10.0,Long,Gourmet,Far
2,3,120,15,3.0,Short,Cheap,Close
3,4,600,60,8.0,Long,Gourmet,Far
4,5,300,20,6.0,Short,Expensive,Medium
5,6,150,50,10.0,Long,Cheap,Far
6,7,500,28,9.0,Medium,Gourmet,Far
7,8,220,35,4.0,Medium,Expensive,Medium

In [ ]:
#unique categories
print(df['Price_Category'].unique())

['Expensive' 'Gourmet' 'Cheap']

In [ ]:
# Count of Unique categories
print(df['Price_Category'].value_counts())

Price_Category
Expensive    3
Gourmet      3
Cheap        2
Name: count, dtype: int64